/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.collinscoding.puzzle

import com.collinscoding.puzzle.kakuro.KakuroBorder
import com.collinscoding.puzzle.minesweeper.CellState
import com.collinscoding.puzzle.minesweeper.Minesweeper
import java.io.File

fun main(args: Array<String>) {
    val sweeper = Minesweeper(13)
    sweeper.parse(File("game.sweeper"))
    sweeper.checkMines()
    println(sweeper.getMines())
    println(sweeper.getGuesses())
}
